// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDL8hamVu3CSrFDY8ETnepTOns5GwnmLx4',
    appId: '1:1032221157256:android:f8fe016572c977cb497c3d',
    messagingSenderId: '1032221157256',
    projectId: 'app-financeiro-c8cfc',
    storageBucket: 'app-financeiro-c8cfc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHIbqva7eRY-ysTgoebNPnCXn52vYn7k8',
    appId: '1:1032221157256:ios:9ac3c29d9139467a497c3d',
    messagingSenderId: '1032221157256',
    projectId: 'app-financeiro-c8cfc',
    storageBucket: 'app-financeiro-c8cfc.appspot.com',
    androidClientId: '1032221157256-2usbkmj9r65161ovoit56c8svu1figor.apps.googleusercontent.com',
    iosClientId: '1032221157256-3s707obj5rcsp1s3k1dae24la6cq6qdv.apps.googleusercontent.com',
    iosBundleId: 'com.example.appFinanceiro',
  );

}